/***********************************************************************/
/*                                                                     */
/*  FILE        :en6A.c                                                */
/*  DATE        :Fri, Jun 17, 2022                                     */
/*  DESCRIPTION :Main Program                                          */
/*  CPU TYPE    :H8/3694F                                              */
/*                                                                     */
/*  This file is generated by Renesas Project Generator (Ver.4.16).    */
/*                                                                     */
/***********************************************************************/

#include "fan.h"
#include "lcd.h"
#include "ad.h"

void main(void);
#ifdef __cplusplus
extern "C" {
void abort(void);
}
#endif

void main(void)
{
	initFan();
    InitLcd();
    initAD();	
	while(1){
		getADVal();
		
    	LcdXY(1,1);
		LcdPuts("RV2; ");
		
		putLCDNumber(4,(unsigned int)g_adRV2);

		LcdXY(1,2);
		LcdPuts("RV3; ");
		putLCDNumber(4,(unsigned int)g_adRV3);	

		setFanLevel((unsigned int)(g_adRV2<<8));
	}
}

#ifdef __cplusplus
void abort(void)
{

}
#endif
